#!/usr/bin/env python3
from __future__ import annotations

import json
import os
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

import acceptance_extensions
import platform_runner


def required(name: str) -> str:
    value = os.environ.get(name, "").strip()
    if not value:
        raise RuntimeError(f"required environment variable is missing: {name}")
    return value


def ensure_faketime_library() -> Path:
    candidates = sorted(Path("/usr/lib").glob("**/faketime/libfaketime.so.1"))
    if not candidates:
        subprocess.run(["sudo", "apt-get", "update"], check=True)
        subprocess.run(["sudo", "apt-get", "install", "-y", "--no-install-recommends", "libfaketime"], check=True)
        candidates = sorted(Path("/usr/lib").glob("**/faketime/libfaketime.so.1"))
    if not candidates:
        raise RuntimeError("libfaketime.so.1 was not found after installation")
    return candidates[0].resolve()


def install_exact_harness_adapter() -> None:
    original_load_harness = platform_runner.load_harness
    faketime_library = ensure_faketime_library()

    def load_harness_with_exact_metadata() -> Any:
        harness = original_load_harness()
        harness.PLATFORM_REF = required("PLATFORM_REF")
        harness.GATEWAY_REF = required("GATEWAY_REF")
        harness.CANARY_REF = required("CANARY_REF")
        harness.OTCLIENT_REF = required("OTCLIENT_REF")
        harness.OTCLIENT_BUILD_RUN = int(required("SOURCE_BUILD_RUN"))
        harness.OTCLIENT_BUILD_ARTIFACT_ID = int(required("OTCLIENT_ARTIFACT_ID"))
        harness.OTCLIENT_BUILD_ARTIFACT_DIGEST = required("OTCLIENT_ARTIFACT_DIGEST")

        original_harness_docker = harness.docker
        oauth_probe_ip_counter = 0

        def docker_with_platform_faketime_mount(*args: str, **kwargs: Any) -> Any:
            nonlocal oauth_probe_ip_counter
            normalized = list(args)
            if normalized and normalized[0] == "create":
                image_index = next(
                    (index for index, value in enumerate(normalized) if value.endswith("-platform:latest")),
                    None,
                )
                if image_index is not None:
                    normalized[image_index:image_index] = [
                        "-v",
                        f"{faketime_library}:/usr/local/lib/libfaketime.so.1:ro",
                    ]
            if normalized and normalized[0] == "run" and "/harness/oauth_probe.py" in normalized and "--ip" not in normalized:
                oauth_probe_ip_counter += 1
                if oauth_probe_ip_counter > 120:
                    raise RuntimeError("OAuth probe IP allocation exceeded the reserved rehearsal range")
                network_index = normalized.index("--network")
                normalized[network_index + 2:network_index + 2] = [
                    "--ip",
                    f"10.201.0.{100 + oauth_probe_ip_counter}",
                ]
            return original_harness_docker(*normalized, **kwargs)

        harness.docker = docker_with_platform_faketime_mount
        original_platform_env = harness.Rehearsal.platform_env
        original_start_platform = harness.Rehearsal.start_platform
        original_write_nginx_config = harness.Rehearsal.write_nginx_config
        original_prepare_canary_config = harness.Rehearsal.prepare_canary_config

        def platform_env_with_trusted_proxy(self: Any, previous: bool) -> list[str]:
            env = original_platform_env(self, previous)
            env.extend(["-e", "TRUSTED_PROXIES=10.201.3.0/24"])
            time_offset = getattr(self, "platform_time_offset", None)
            if time_offset:
                env.extend(
                    [
                        "-e",
                        "LD_PRELOAD=/usr/local/lib/libfaketime.so.1",
                        "-e",
                        f"FAKETIME={time_offset}",
                        "-e",
                        "FAKETIME_DONT_FAKE_MONOTONIC=1",
                    ]
                )
            return env

        def prepare_canary_config_with_game_sessions(self: Any) -> None:
            original_prepare_canary_config(self)
            config_path = self.canary_source / "config.lua"
            text = config_path.read_text(encoding="utf-8")
            password_auth = 'authType = "password"'
            if text.count(password_auth) != 1:
                raise harness.RehearsalError("expected exactly one password authType generated by the base harness")
            config_path.write_text(text.replace(password_auth, 'authType = "session"', 1), encoding="utf-8")

        def write_nginx_config_with_forwarded_client(self: Any, name: str, upstream: str) -> Path:
            path = original_write_nginx_config(self, name, upstream)
            text = path.read_text(encoding="utf-8")
            marker = "    proxy_set_header X-Forwarded-Proto https;\n"
            if marker not in text:
                raise harness.RehearsalError(f"proxy config {name} is missing the forwarded-proto marker")
            path.write_text(
                text.replace(
                    marker,
                    marker + "    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n",
                    1,
                ),
                encoding="utf-8",
            )
            return path

        def start_platform_with_fresh_readiness(self: Any, *, previous: bool) -> None:
            bootstrap_path = self.evidence / "platform-bootstrap.json"
            bootstrap_path.unlink(missing_ok=True)
            original_start_platform(self, previous=previous)
            for _ in range(90):
                health = harness.docker(
                    "run",
                    "--rm",
                    "--network",
                    self.networks["platform_service"],
                    "curlimages/curl:8.12.1",
                    "curl",
                    "-fsS",
                    "http://platform-backend:8080/health",
                    check=False,
                )
                if health.returncode == 0:
                    return
                time.sleep(1)
            raise harness.RehearsalError("Platform did not become HTTP-ready after restart")

        def validate_oauth_matrix_with_real_expiry(self: Any) -> None:
            if self.run_oauth_probe(["matrix", "--output", "/evidence/oauth-pkce-result.json"]) != 0:
                raise harness.RehearsalError("OAuth PKCE negative matrix failed")

            secret_dir = self.temp / "secret-code"
            secret_dir.mkdir(exist_ok=True)
            secret_path = secret_dir / "code.json"
            if self.run_oauth_probe(
                ["issue-code", "--secret-output", "/secret/code.json"],
                secret_mount=secret_dir,
            ) != 0:
                raise harness.RehearsalError("could not issue authorization code for expiry test")

            try:
                self.platform_time_offset = "+2h"
                self.start_platform(previous=True)
                if self.run_oauth_probe(
                    [
                        "exchange-code",
                        "--secret-input",
                        "/secret/code.json",
                        "--output",
                        "/evidence/oauth-code-expiry.json",
                    ],
                    secret_mount=secret_dir,
                ) != 0:
                    raise harness.RehearsalError("expired authorization code was not rejected")
            finally:
                self.platform_time_offset = None
                self.start_platform(previous=True)
                secret_path.unlink(missing_ok=True)

        harness.Rehearsal.platform_env = platform_env_with_trusted_proxy
        harness.Rehearsal.prepare_canary_config = prepare_canary_config_with_game_sessions
        harness.Rehearsal.write_nginx_config = write_nginx_config_with_forwarded_client
        harness.Rehearsal.start_platform = start_platform_with_fresh_readiness
        harness.Rehearsal.validate_oauth_matrix = validate_oauth_matrix_with_real_expiry
        acceptance_extensions.install(harness)

        extended_sensitive_scan = harness.Rehearsal.sensitive_scan

        def stable_sensitive_scan(self: Any) -> dict[str, Any]:
            try:
                result = extended_sensitive_scan(self)
            except harness.RehearsalError:
                result = None
            if isinstance(result, dict):
                return result
            result_path = self.evidence / "sensitive-log-scan.json"
            if not result_path.exists():
                return {"schema_version": 1, "status": "FAIL", "findings": ["scan_result_missing"]}
            decoded = json.loads(result_path.read_text(encoding="utf-8"))
            return decoded if isinstance(decoded, dict) else {"schema_version": 1, "status": "FAIL", "findings": ["scan_result_invalid"]}

        harness.Rehearsal.sensitive_scan = stable_sensitive_scan
        return harness

    platform_runner.load_harness = load_harness_with_exact_metadata


def update_retained_evidence() -> None:
    evidence_dir = Path(required("REHEARSAL_EVIDENCE_DIR"))
    evidence_dir.mkdir(parents=True, exist_ok=True)

    revisions_path = evidence_dir / "runtime-revisions.json"
    if revisions_path.exists():
        revisions = json.loads(revisions_path.read_text(encoding="utf-8"))
    else:
        revisions = {"schema_version": 1, "build": {}, "components": {}}
    revisions["build"] = {
        "workflow": "Native Auth Ephemeral Cutover Rehearsal",
        "workflow_run": os.environ.get("GITHUB_RUN_ID", "local"),
        "gateway_otclient_source_build_run": required("SOURCE_BUILD_RUN"),
        "canary_source_build_run": required("CANARY_BUILD_RUN"),
    }
    revisions["components"] = {
        "platform": {"repository": "blakinio/Oteryn-Platform", "source_sha": required("PLATFORM_REF")},
        "gateway": {"repository": "blakinio/Oteryn-Platform", "source_sha": required("GATEWAY_REF")},
        "canary": {"repository": "blakinio/canary", "source_sha": required("CANARY_REF"), "runtime_auth_type": "session"},
        "otclient": {"repository": "blakinio/otclient", "source_sha": required("OTCLIENT_REF")},
        "canary_harness": {"repository": "blakinio/canary", "source_sha": required("CANARY_HARNESS_REF")},
    }
    revisions_path.write_text(json.dumps(revisions, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    digests_path = evidence_dir / "artifact-digests.json"
    if digests_path.exists():
        digests = json.loads(digests_path.read_text(encoding="utf-8"))
    else:
        digests = {"schema_version": 1}
    digests["gateway_otclient_source_build_run"] = int(required("SOURCE_BUILD_RUN"))
    digests["canary_source_build_run"] = int(required("CANARY_BUILD_RUN"))
    digests["gateway_source_build_artifact_id"] = int(required("GATEWAY_ARTIFACT_ID"))
    digests["gateway_source_build_artifact_digest"] = required("GATEWAY_ARTIFACT_DIGEST")
    digests["canary_source_build_artifact_id"] = int(required("CANARY_ARTIFACT_ID"))
    digests["canary_source_build_artifact_digest"] = required("CANARY_ARTIFACT_DIGEST")
    digests["otclient_source_build_artifact_id"] = int(required("OTCLIENT_ARTIFACT_ID"))
    digests["otclient_source_build_artifact_digest"] = required("OTCLIENT_ARTIFACT_DIGEST")
    digests["otclient_source_build_run"] = int(required("SOURCE_BUILD_RUN"))
    digests_path.write_text(json.dumps(digests, indent=2, sort_keys=True) + "\n", encoding="utf-8")


if __name__ == "__main__":
    install_exact_harness_adapter()
    exit_code = platform_runner.main()
    update_retained_evidence()
    sys.exit(exit_code)
